### ISSUE TITLE
Add radial profile plot?

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#101]
Would it be possible to add a radial profile plot to hplot (like the one that used to be available in cplot in the c version of the ULTRACAM pipeline)? This would be really useful when commissioning. I think Ingrid may have requested something similar in slack a while ago, but that was for nrtplot (?).

**Comment by trmrsh** [comment]
I didn't do this since one can simply replicate the process with "combine", but I guess I might as well add this

**Comment by vikdhillon** [comment]
Ah yes, sorry - I think this is what I ended up using. (By the way, I think
this comment is for a different issue - the one about the missing hf option
in makebias, not the radial profile plot?)

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---
