### ISSUE TITLE
Makebias doesn't have a hf option for the input source

### ISSUE THREAD

**Issue by Alex-J-Brown** [HiPERCAM/hipercam#111]
I've noticed while trying to reduce some GTC-OSIRIS data using the pipeline (and therefore requiring the 'hf' option in order to supply a list of files) that 'makebias' is the only one of the makexxxx and reduce scripts that doesn't have the file list option.

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hipercam/commit/75fa2298b0a7553868749b053db6a62890bac278
