### ISSUE TITLE
y position plot in reduce does not autoscale when fixed=no

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#22]
The y-position plot in reduce does not seem to autoscale correctly when y_fixed=no in the reduce file.

**Comment by trmrsh** [comment]
I couldn't verify this; in the example I ran, it seemed to work OK. If you could give me an explicit example I might be able to progress.

**Comment by vikdhillon** [comment]
Hi Tom,
I'm pretty sure I saw this on the NN Ser data we got on the last night (Feb
14/15) - not had a chance yet to get the data on disk for you to copy over.
Cheers,
Vik.


---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by StuartLittlefair** [comment]
This still seems to be an issue. The reduce position plot shows jumps in the y position which are clearly not present if one plots the y positions in the log file. The jumps seem to coincide with when the reduce position plot autoscales. The autoscaling also doesn't seem to work all the time, sometimes truncating the data at the top of plot.

**Comment by trmrsh** [comment]
Think I have spotted a problem that might explain this. Have pushed a fix. If you re-install, let me know if it works or not. Will move onto other issues until then

**Comment by StuartLittlefair** [comment]
sorry @trmrsh - this does not appear to have fixed it

**Comment by trmrsh** [comment]
bugger. is it really only the y-position, or is the x-positoin screwed too (the bug I fixed affected both)?

**Comment by StuartLittlefair** [comment]
it really does only look like the y position; Vik's never seen it in x

**Comment by trmrsh** [comment]
OK, think I have it this time! Have pushed the fix. Let me know.

**Comment by StuartLittlefair** [comment]
looks good! closing...
