### ISSUE TITLE
rtplot crashed when binning 4x4 using full frame with overscan

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#26]
when taking full frame images with overscan, hdriver warns the user that some columns of overscan and real data will be mixed. When trying to plot the data with rtplot, however, it crashes with the following error:

hipercam{observer}32: rtplot
run - run name [run0021]: \
Traceback (most recent call last):
  File "/home/observer/.local/bin/rtplot", line 11, in <module>
    load_entry_point('hipercam==0.7.dev7+g994a2b5', 'console_scripts', 'rtplot')()
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/scripts/rtplot.py", line 448, in rtplot
    with spooler.data_source(source, resource, first) as spool:
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/spooler.py", line 310, in data_source
    return HcamServSpool(resource, first)
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/spooler.py", line 259, in __init__
    self._iter = hcam.Rdata(run, first, True)
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/hcam.py", line 779, in __init__
    Rhead.__init__(self, fname, server)
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/hcam.py", line 306, in __init__
    HCM_NPSCAN)
hipercam.core.HipercamError: X-binning factor not a divisor of 50 with prescan is undefined
hipercam{observer}33:

**Comment by trmrsh** [comment]
Ah, Stu, I had understood from you that this was not allowed, i.e. that hdriver would not allow a frame to be taken with a prescan / osverscan indivisible by NX / NY?

I think it's OK to have a more general behaviour but I am unsure exactly what to do in this case because of the mixed prescan/overscan data thingy.  I assume this isn't a show stopper for observing Vik, although annoying? If you could make a small example file available it would be helpful for fixing this.

**Comment by vikdhillon** [comment]
Hi Tom,
Apologies, I meant to get you some example data but failed to remember
before I shut everything down.
Stu - any chance we can get some of this using the simulator running in the
lab downstairs?
Cheers,
Vik.


---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by trmrsh** [comment]
If you get a chance, can you confirm this issue and get some example data if it is still a problem?

**Comment by trmrsh** [comment]
I don't think its a bug; Stu and I agreed not to try to implement anything more than 2 because it is so likely that we will screw up exactly what pixels are being stored where when the binning factor does not divide into 50. So I have not tried to fix the pipeline for it.

**Comment by trmrsh** [comment]
OK, I guess you need to add this as an hdriver issue?

**Comment by trmrsh** [comment]
Closing this one
