### ISSUE TITLE
setaper is broken on some backends (DRPC in particular)

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#31]
There's an issue with [this line](https://github.com/HiPERCAM/hipercam/blob/master/hipercam/scripts/setaper.py#L449), that causes setaper to crash on the DRPC with an error

```
RuntimeError: adjustable='datalim' is not allowed when both axes are shared
```

This appears to be a problem with setting the aspect ratio to equal and ```adjustable``` to ```datalim``` with shared axes. Getting rid of the ```adjustable``` argument to that line, and the similar line above fixes the bug and allows setaper to run, but may not be an optimal solution

**Comment by trmrsh** [comment]
hi stu, yes I think this is related to a bug Vik reportedin another context. Are you able to live with it? Obvious solution is to wrap a try-except statement, but I think the aspect ratio and datalim are useful. I will try to see if there is a workaround. Which backend fails?

**Comment by trmrsh** [comment]
closing this as I think I have fixed it
