### ISSUE TITLE
Please could rtplot show the integrated counts in a profile fit?

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#33]
For quick and dirty photometry it would be useful to know the area under the profile fit in counts when profit=y. Currently, lots of stats are output about the profile fit, but not the area.

**Comment by trmrsh** [comment]
will do

**Comment by trmrsh** [comment]
have added "counts" to the output which is the total sum of the fitted profile, i.e. not the actual sum over the data in some aperture. It's not perfect, but if the fit is reasonable, it should give you a ballpark idea.
