### ISSUE TITLE
exposure time output by rtplot

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#35]
Would it be possible to write out the exposure time in the rtplot terminal output when it plots a frame? We do this in the ultracam pipeline, but the hipercam pipeline only outputs the GPS time. I would find this really useful as a quick check on what the exposure time actually is.

**Comment by trmrsh** [comment]
yes, sure. I hadn't done it because of the multiple different exposure times possible for each CCD. Shall I just report the g-band one as the one least likely to require an NSKIP?

**Comment by trmrsh** [comment]
leave it to me

**Comment by trmrsh** [comment]
Have done this now and pushed the mods to github. It reports all the exposure times of the displayed CCDs.
