### ISSUE TITLE
makeflat causes machine death 

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#36]
Not only does it write a very large number of temporary files, but memory usage is extremely high (13Gb on my mac).

Seems to be impossible to use when grabbing from the server.

**Comment by trmrsh** [comment]
how many files were you trying to combine? Bit surprised; not sure it can be working as I expected. The temporary files should not be that much of an issue in that it is just 1 per image I think. Will look into it.

**Comment by trmrsh** [comment]
ok must be doing something wrong. strange; i thought i had it working.

**Comment by trmrsh** [comment]
OK makeflat is fixed. Very sorry about this one because I had clearly never run it even once as it had a couple of absolutely terminal bugs. It was reading the same file into memory in an infinite loop. Seems to work OK now, but obviously let me know if you encounter problems. Closing this for now.
