### ISSUE TITLE
Fixed aperture radii not overridden by reduce file values 

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#37]
In the ULTRACAM pipeline, when using fixed apertures, it is possible to override the values in the setaper file by setting the corresponding lines in the reduce file (by setting the min and max radii to be the same value). In the HiPERCAM pipeline, one has to edit the setaper file to change the fixed aperture radii. It would be useful to make HiPERCAM behave in the same way as ULTRACAM, if possible.

**Comment by trmrsh** [comment]
absolutely; shouldn't be doing that. will look into it.

**Comment by trmrsh** [comment]
Had same problem in May run on an exoplanet. Now fixed.
