### ISSUE TITLE
Feature Request: efficient reading of large log files

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#40]
It would be nice if the ```HLog``` object supported lazy loading so that we could read in a large log file without using an enormous amount of memory. 

This might take some redesign of the ```Hlog``` object though

**Comment by trmrsh** [comment]
I have altered the Hlog loading to reduce its memory footprint. Not exactly what you were looking for, but it should help. For really large files, I will at some point make a converter to FITS with one HDU per CCD. Again not perfect, but it would have to be fairly extreme to make these too large. Closing for the moment.
