### ISSUE TITLE
Feature request: add defringe option to reduce

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#41]
Since we are always taking z-band images now, we ought to be able to defringe our data as we reduce it. ```reduce``` should probably take an option for a fringe frame as well as the other calibrations. 

In addition, should we add flat fields and fringe frames to ```grab```? Or write a separate function to extract and calibrate frames?

**Comment by trmrsh** [comment]
Finally done on all counts!
