### ISSUE TITLE
reduce should output results in electrons rather than counts

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#42]
Given that we have 4 readout channels, each with a different (by ~5-10%) gain, it would be much safer to output results in electrons rather than counts so that, for example, it doesn't matter as much if the comparison star and target change quadrants.

**Comment by trmrsh** [comment]
closing this one: in fact on further reflection I realised that normal flat-fielding effectively should allow for this since if the gain varies then so do do the flats.
