### ISSUE TITLE
Real time reduction of ULTRACAM data with HiPERCAM pipeline haulting prematurely

### ISSUE THREAD

**Issue by SGParsons** [HiPERCAM/hipercam#43]
When using the HiPERCAM reduction pipeline on live ULTRACAM data all routines will end when they reach the current frame and won't wait for a new frame to appear. The pipeline doesn't give any error messages or appear to crash. However, we set TWAIT=10 and TMAX=20 but the pipeline instantly exits as soon as it hits the last frame.

**Comment by trmrsh** [comment]
I can't immediately see what's causing this. (If you feel brave, the relevant routine is in ucam.py and is Rdata.__call__)   I have added a print statement at a relevant point, and if you update the installation, try it out with the server running (you don't need to be taking data -- just accessing the data via the server). Send me what gets printed out in the final few frames.

**Comment by trmrsh** [comment]
think I have fixed this one and so I am closing it.
