### ISSUE TITLE
rtplot could use a NSKIP option

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#44]
At the moment rtplot has no chance of keeping up with drift mode runs.

Perhaps it could gain an NSKIP option, so it wouldn't try to plot every frame?

**Comment by trmrsh** [comment]
This is exactly what the first=0 option in the ULTRACAM pipeline accomplishes, i.e. it always plots the last frame. This is also how I would like the hipercam pipeline to work. If it doesn't (and I seem to remember it doesn't), it's really a matter of the inability to work out the final frame number, or do you disagree? If that is not fixable, then I could put in an NSKIP, but I would regard it as a stopgap measure. Let me know.

**Comment by StuartLittlefair** [comment]
agreed - this is an issue with first=0. 

I'll try and take a look at it whilst I'm out.

**Comment by StuartLittlefair** [comment]
Leaving this closed, since this is not an issue with hipercam, but the improvements I have made to working out the final frame number in ```hcam_drivers``` have not helped. The underlying issues are that:

1. the frame number reported by the eso s/w is not the number of frames written to disc, because of buffering.
2. we can't use the file size to estimate the last frame, because of https://github.com/HiPERCAM/hiperCamCCD/issues/5

**Comment by trmrsh** [comment]
Can you see any way through this? Does the size of FITS files always increase by 2880 bytes? If so this could be used to access not the last perhaps but nearly the last (I think). Otherwise, hateful though it would be, I would have to suggest moving to an ULTRACAM-like model in which the data get written to a simple binary file, but I don't know if this would even be possible.

**Comment by StuartLittlefair** [comment]
No, not unless Gao can find a fix to https://github.com/HiPERCAM/hiperCamCCD/issues/5, and I don't think he's very far along. 

This isn't really a problem with the FITS file format, but the way the ESO s/w works. The problem is that fixing this is a massive job that begins with understanding the detailed inner workings of the ESO s/w.
