### ISSUE TITLE
2 warning messages while running reduce

### ISSUE THREAD

**Issue by matthu7777** [HiPERCAM/hipercam#51]
Warning messages while running reduce on ultracam data. 

I suspect these might be because of trying to fit weird data (this was Stu's binary inside a planetary nebula so perhaps that caused fitting problems), as we haven't seen them since. But I'll copy the messages below in case it is anything more serious.

One message seemed to come up every second frame, always referring to a problem fitting on CCD 1. Example:

Frame 51: 2018-06-15T04:03:20.851 [OK]; ccd 1: -17.00 to 51.00, ccd 2: -14.00 to 27.00
CCD 1, aperture 1, fit failed, error = Fitted position (387.7,193.4) too close to or beyond edge of search window = Winhead(llx=367, lly=163, nx=21, ny=21, xbin=1, ybin=1, head="CCDNAME = 'Red CCD '                                                            \nTIMSTAMP= '2018-06-15T04:03:26.610'                                             \nMJDUTC  =    58284.16905798115                                                  \nEXPTIME =    5.734942852443466                                                  \nGOODTIME=                    T                                                  \nMJDOKWHY= ''                                                                    ")

The other message came up intermittently, but often for several frames in a row. Example:
Frame 41: 2018-06-15T04:02:23.261 [OK]; ccd 1: -17.00 to 52.00, ccd 2: -14.00 to 28.00
CCD 1, aperture 1, fit failed, error = Negative covariance in fitGaussian

**Comment by trmrsh** [comment]
Yes, the first means what it says: i.e. that the position measured for the target fell outside the region of the search window which is taken to be a problem, and no extraction is carried out (the data/error will be 0/-1 for this). It could well be a problem with the nebula background that is beyond the scope of the pipeline. It could be a case where you would be better off linking to a target away from the nebula (if possible). The second could be related, although its basically an indication of a failed attempt to fit the profile. Again linking the aberrant aperture might help you (no profile fit is attempted if an aperture is linked). Am closing this.
