### ISSUE TITLE
rtplot segmentation fault

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hipercam#52]
Using rtplot on any existing hipercam data file on an Arch Linux system causes a segmentation fault (core dumped). No plot windows appear.

hipercam and trm-pgplot are git pull updated to version as of 20Jun2018 19:00 UTC

thorin{star}14: rtplot run0019.fits
first - first frame to plot [1]: 
ccd - CCD(s) to plot [0 for all] [0]: 
nx - number of panels in X [3]: 
bias - bias frame ['none' to ignore] [none]: 
defect - defect file ['none' to ignore] [none]: 
setup - display current hdriver window settings [False]: 
msub - subtract median from each window? [False]: 
iset - set intensity a(utomatically), d(irectly) or with p(ercentiles)? [a]: 
xlo - left-hand X value [-50.0]: min
xhi - right-hand X value [2099.0]: max
ylo - lower Y value [-8.0]: min
yhi - upper Y value [1033.0]: max
Segmentation fault (core dumped)

dmesg shows...
[  607.152654] rtplot[2311]: segfault at 0 ip 000014e872f20ba1 sp 00007ffd95a8ed10 error 6 in libgfortran.so.5.0.0[14e872d09000+277000]

/usr/lib/libgfortran.so.5 is from the core/gcc-libs package, which is version 8.1.1+20180531-1

**Comment by trmrsh** [comment]
Has it ever worked on this system? "yhi" is the last argument to be read, so beyond that point it does something. I would be fairly sure that it has to be something to do with PGPLOT given the gfortran error. Does PGPLOT itself work on the system? This is not a problem that I have on the system here so it
will be a difficult one to diagnose. If you or Stu could stick in a load of print statements to narrow down where the problem occurs, that could help. At a guess, it could be an issue with my cythonised version of PGPLOT so if you could work out exactly which routine is failing and the arguments that are being sent to it (types, sizes of arrays if relevant), that would be a significant help.

**Comment by paulkerry1** [comment]
I cannot replicate this issue using the same setup with the same data files on an alternative Arch Linux system, so I'm closing this.Sorry for the noise.

Cheers
Paul.
