### ISSUE TITLE
HCM files should have FITS WCS added to extensions

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#55]
The information is present in the .fits files written by the instrument to create this programatically.

```
RA      = '12:25:51' / Telescope Right Ascension (HH:MM:SS.SSS)                 
DEC     = '+33:32:27' / Telescope Declination (DD:MM:SS.SS)                     
RADEG   =           186.460785 / RA of the instrument scientific aperture in    
DECDEG  =             33.54078 / DEC of the instrument scientific aperture i    
ELEVAT  =               51.400 / Telescope Elevation (degrees)                  
AZIMUTH =               71.300 / Azimuth (degrees)                              
AIRMASS =                 1.28 / Airmass                                        
LST     = '+09:26:24.356' / Local Sidereal Time (HH:MM:SS.SSS)                  
INSTRPA =                169.0 / Position angle (E of N, degrees)  
```

One potential SNAFU is the relationship between ```INSTRPA``` and ```SKYPA``` ever since the first commissioning run this is supposed to be 0 degrees, but we've had slippage in the rotator. Perhaps this difference should be written to the raw fits data, and read from a configuration item in the HiPERCAM GUI?

**Comment by trmrsh** [comment]
the rotator offset is variable isn't it? i.e. we never really know what it is. I will have do some investigative work to see if I can work it out in a few example cases.

**Comment by StuartLittlefair** [comment]
apparently this is now fixed, so i should be a well known value...

**Comment by trmrsh** [comment]
With the advent of "joinup" this is more-or-less fixed I think, so closing it.
