### ISSUE TITLE
reduce doesn't allow you to turn both light curve and image plotting off

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#57]
To try to speed up reduction of a long drift-mode run, I tried turning both image and light curve plotting off, causing reduce to fail with the error below. The command below works fine if instead lplot=true:

hipercam{observer}233: reduce lplot=false implot=false \\
Frame 3: 2018-10-04T20:44:30.4394556 [NOK]
/home/observer/.local/lib/python3.5/site-packages/hipercam/reduction.py:992: UserWarning: '** fit_half_width' < 5*max(xbin,ybin) (24.0 vs 40) ==> small windows for profile fits. Advise increasing its value in the reduce file if possible.
  rfile['apertures']['fit_half_width'], 5*max(xbin, ybin)
CCD 1, reference aperture 1, fit failed, will abort extraction. Error = no peak higher than 10.0 found; highest = 1207.8 (background = 1198.0)
 *** WARNING: CCD 1: no measured FWHM to re-size apertures or carry out optimal extraction; no extraction possible
CCD 4, aperture 2, fit failed, error = no peak higher than 5.0 found; highest = 1214.2 (background = 1212.0)
CCD 3, aperture 2, fit failed, error = no peak higher than 5.0 found; highest = 1512.4 (background = 1514.0)
CCD 2, aperture 2, fit failed, error = no peak higher than 5.0 found; highest = 1133.1 (background = 1134.0)
CCD 5, aperture 2, fit failed, error = no peak higher than 5.0 found; highest = 1193.4 (background = 1191.0)
 *** WARNING: CCD 1, aperture 1: no FWHM could be measured
 *** WARNING: CCD 1, aperture 2: no FWHM could be measured
 *** WARNING: CCD 2, aperture 2: sky aperture overlaps edge of window
 *** WARNING: CCD 4, aperture 2: sky aperture overlaps edge of window
 *** WARNING: CCD 5, aperture 1: sky aperture overlaps edge of window
Traceback (most recent call last):
  File "/home/observer/.local/bin/reduce", line 11, in <module>
    sys.exit(reduce())
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/scripts/reduce.py", line 419, in reduce
    tkeep, lbuffer, xbuffer, ybuffer, tbuffer, sbuffer
UnboundLocalError: local variable 'lbuffer' referenced before assignment
hipercam{observer}234:

**Comment by trmrsh** [comment]
hope i have fixed this one
