### ISSUE TITLE
hlog.py period folding issue

### ISSUE THREAD

**Issue by ghost** [HiPERCAM/hipercam#60]
The line to fold the data (line 662) is currently:
`fold_time = (((self.t - t0 * period) / period) % 1)`
which will do:
1. a = t0 * period
2. b = self.t - a
3. b / period

following BIDMAS.

I think we want that to happen the other way around, i.e.
1. a = self.t - t0
2. b = a / period
3. b % 1.

So:
`fold_time = ( (self.t - t0) / period ) % 1.`

**Comment by trmrsh** [comment]
Yes, for sure. I have fixed this and pushed the fix to github. Ask Paul for a re-install if you need it immediately. Thanks.
