### ISSUE TITLE
reduce not functioning correctly with ULTRASPEC data

### ISSUE THREAD

**Issue by SGParsons** [HiPERCAM/hipercam#62]
Reduce doesn't work properly with ULTRASPEC data, it skips right to the end regardless of where I tell it to start:

ultracam@observer:~/reduce/20181210/hcam> reduce
rfile - reduce file [run020]: 
run - run name [/media/observer/ultracam_usb42/2018_12_10/run020]: 
first - first frame to reduce [1]: 2
log - name of log file to store results [run020]: 
tkeep - number of minute of data to keep in internal buffers (0 for all) [0.0]: 
lplot - do you want to plot light curves? [True]: 
implot - do you want to plot images? [True]: 
msub - subtract median from each window? [True]: 
iset - set intensity a(utomatically), d(irectly) or with p(ercentiles)? [p]: 
plo - lower intensity limit percentile [1.0]: 
phi - upper intensity limit percentile [95.0]: 99
xlo - left-hand X value [0.0]: 
xhi - right-hand X value [1057.0]: 
ylo - lower Y value [0.0]: 
yhi - upper Y value [1073.0]: 
Have reduced up to the last frame set (=0)
reduce finished

ultracam@observer:~/reduce/20181210/hcam> reduce first=100 \\
Have reduced up to the last frame set (=0)
reduce finished

It just says reduce finished but it never actually reduced anything, I just get two blank xserve windows appear

**Comment by trmrsh** [comment]
can you try specifying "last=10000" on the command line (or via prompt). I think this might be an unrelated bug

**Comment by SGParsons** [comment]
Okay, that has worked and everything looks fine with the resulting light curve data, which matches the ULTRACAM pipeline version. Times match those from the ULTRACAM pipeline. As far as I can see everything is working fine now, except that setaper is slow across the network

**Comment by SGParsons** [comment]
The time taken to display the initial image is fairly similar for matplotlib vs. pgplot, although pgplot is certainly faster. Getting statistics on the image with matplotlib is instantaneous. The real slow down comes if you want to zoom in on a region with matplotlib because the image can't keep up while your drawing the box to zoom in. Neither can the pan tool keep up, you have to make very slow movements

**Comment by trmrsh** [comment]
OK, well, I don't think I have the time to get it fixed this run, although at least it seems to be working enough to let Amornrat try on her laptop. I will have to see if there is a work around. I guess a PGPLOT option is not such a bad thing for ULTRASPEC given it's only the once CCD.

**Comment by StuartLittlefair** [comment]
Think we can close this now - the pipeline is totally useable even from Sheffield, over VNC.
