### ISSUE TITLE
Problems reading in log files generated from ULTRACAM pipeline

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#63]
I have problems reading in some ULTRACAM log files. Not all, just some. The error is raised when attempting to convert the packed bytes into a numpy structured array.

For example, this line causes an issue:

```
 '       1 58468.9241808524 0  4.700700 1   2.508   2.394  1  396.3277  108.9689    0.0000    0.0000 -1.0000 -1.0000     3270.4    91.9     93.22 942    2  0  0  2  356.3611  480.2649  356.3611  480.2649  0.0064  0.0065    66328.1   294.2    100.20 856    1  0  0\n'
```

Looking at the conversion of the MJD field alone we have:

```python
In [75]: hlog[cnam][0][:8]                                                                                                              
Out[75]: b'\x15\xb9\xe3\x92\x9d\x8c\xec@'

In [76]: struct.unpack('<d', hlog[cnam][0][:8])                                                                                         
Out[76]: (58468.9241808524,)

In [77]: np.array(hlog[cnam][0][:8], dtype='<f8')                                                                                       
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-77-ebe45d8f836e> in <module>
----> 1 np.array(hlog[cnam][0][:8], dtype='<f8')

ValueError: could not convert string to float: b'\x15\xb9\xe3\x92\x9d\x8c\xec@'
```

This is beyond my ability to debug. Any clues?

**Comment by StuartLittlefair** [comment]
Forgive me: for clarity I should say that this is an ULTRASPEC run, but I don't think it matters for the bug, as demonstrated by the minimal example above.

**Comment by StuartLittlefair** [comment]
correct...

**Comment by trmrsh** [comment]
where does it collapse? Just tried

ulg = hcam.hlog.Hlog.from_ulog('run043.log')

without a problem

**Comment by StuartLittlefair** [comment]
Which numpy version?

It’s the np.array() line that dies.

Stuart Littlefair
Dept. of Physics & Astronomy
Univ. of Sheffield, Sheffield, S3 7RH

email: s.littlefair@shef.ac.uk
Phone: +44 114 2224525
Sent from my iPhone

On 17 Dec 2018, at 17:09, Tom <notifications@github.com> wrote:

where does it collapse? Just tried

ulg = hcam.hlog.Hlog.from_ulog('run043.log')

without a problem

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HiPERCAM/hipercam/issues/63#issuecomment-447922032>,
or mute
the thread

**Comment by trmrsh** [comment]
1.13.3  I will give it a go on my laptop too.

**Comment by trmrsh** [comment]
fails on my laptop, numpy 1.15.4 ... groan

**Comment by trmrsh** [comment]
If I go

b = struct.pack('d', 34.)
a = np.array([b,],dtype=[('time','<f8'),])

it works but

a = np.array([b,],dtype='<f8')

as you have it doesn't, so I am not sure your snippet is a good test, but I still have a difference between by laptop and system.

tom

**Comment by trmrsh** [comment]
Hi stu, I think I have fixed it (on the master branch), but grateful if you could test both it and the hipercam equivalent 'from_ascii'

tom

**Comment by StuartLittlefair** [comment]
LGTM @trmrsh !

do you know why the byte array approach works when the other one didn't?

**Comment by trmrsh** [comment]
no, although I notes that in the hipercam one I had np.frombuffer(np.array(xxxx), dtype=...) which reminded me that I think I had encountered the same thing and came to a different conclusion. I have altered the hipercam one to be a bytearray as well.
