### ISSUE TITLE
reduce with last=0 not functioning correctly

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#64]
The "last" parameter in rtplot should presumably be set to 0 if one wants to reduce from the first frame (first=1) to the last frame in a run. However, when one does this, one gets the following error in reduce when running from a local file:

vsd@pulsar/local/vsd/tmp/diffuser/reduce> reduce prompt
source - data source [hs, hl, us, ul, hf] [hl]: 
rfile - reduce file [run0021]: 
run - run name [run0021]: 
first - first frame to reduce [1]: 
last - last frame to reduce [0]: 0
twait - time to wait for a new frame [secs] [1.0]: 
tmax - maximum time to wait for a new frame [secs] [10.0]: 
log - name of log file to store results [junk]: 
tkeep - number of minute of data to keep in internal buffers (0 for all) [0.0]: 
lplot - do you want to plot light curves? [True]: 
implot - do you want to plot images? [True]: 
ccd - CCD(s) to plot [0 for all] [0]: 
nx - number of panels in X [5]: 
msub - subtract median from each window? [True]: 
iset - set intensity a(utomatically), d(irectly) or with p(ercentiles)? [p]: 
plo - lower intensity limit percentile [1.0]: 
phi - upper intensity limit percentile [90.0]: 99
xlo - left-hand X value [0.0]: min
xhi - right-hand X value [2049.0]: max
ylo - lower Y value [0.0]: min
yhi - upper Y value [1025.0]: max
Have reduced up to the last frame set (=0)
reduce finished
vsd@pulsar/local/vsd/tmp/diffuser/reduce>

**Comment by trmrsh** [comment]
ah yes, sorry, this was fixed on the "faster" branch but not the main one. Have pushed a fix to it now. Not looking forward to resolving clashed between "faster" and "master".
