### ISSUE TITLE
reduce not working when given a list of files

### ISSUE THREAD

**Issue by SGParsons** [HiPERCAM/hipercam#65]
Trying to reduce a set of .hcm frames with reduce using source=hf, but I get the following error:

Traceback (most recent call last):
  File "/usr/local/python3_modules/bin/reduce", line 11, in <module>
    sys.exit(reduce())
  File "/usr/local/lib/python3.5/dist-packages/hipercam/scripts/reduce.py", line 395, in reduce
    if nframe > last:
UnboundLocalError: local variable 'last' referenced before assignment

Looks like the variable 'last' is never assigned when using the hf option.

**Comment by trmrsh** [comment]
sounds likely. Hang on.

**Comment by trmrsh** [comment]
OK, I think I have fixed it. Will need a 'git pull' and re-install at your end of course.

**Comment by trmrsh** [comment]
Close this issue if it works for you.

**Comment by SGParsons** [comment]
Works fine now
