### ISSUE TITLE
grab with ultracam fileserver

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hipercam#67]
Using grab from the ultracam fileserver doesn't work directly if the run files are not located under /data.

If I try to grab /data1/2019_02_07/run002 then grab fails as it tries to grab...
/data/data1/2019_02_07/run002
and this message appears...
urllib.error.HTTPError: HTTP Error 404: Exception: no_xml: file does not exist

Specifying a relative path to grab works...
% grab
run - run name [../data1/2019_02_27/run002]: 
...
Written frame 3 to run002_003.hcm
...

As that grabs /data/../data1/2019_02_27/run002

Cheers
Paul.

**Comment by trmrsh** [comment]
Hi Paul, I think this is a feature of the FileServer which I didn't write, have never changed and don't really want to change unless this really causes you problems.
