### ISSUE TITLE
README.rst  changes

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hipercam#69]
There are a few modifications needed to the top level README.rst file.

- arrange the third-party list of packages into alphabetical order?
- add "scipy" to the list of requirements as this is needed for fitting.py/window.py/aligntool.py
- matplotlib: typos "In opensuse the package python3-matplotib-qt5 allowing the Qt5Agg backend" -> "In openSUSE, the package python3-matplotib-qt5 enables the Qt5Agg backend." Possibly add a "python3-pyqt5" package reference for Debian based systems.
- requests module: typo "requiest"
- websocket: git cloning of the websocket-client is not needed as websocket-client is available on pypi: remove git info and change reference to websocket-client

Cheers
Paul.

**Comment by trmrsh** [comment]
Done
