### ISSUE TITLE
setaper.py using the TkAgg matplotlib backend

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hipercam#70]
When using the TkAgg matplotlib backend, which maybe has to be used if the preferred Qt5Agg backend and it's libraries cannot be installed on a particular system, the "hand" cursor (i.e. pan mode) is used as default which limits target selection due to obscuration unless pan mode is deselected in the matplotlib window.

The simplest way to fix this is to not set pan mode in setaper.py for TkAgg which will then show a standard "arrow" icon - here's a diff (<=new, >=old)...
 
```
428,429c428
<     if backend != 'TkAgg':
<         toolbar.pan()
---
>     toolbar.pan()
```

Alternatives to the above are to set and use toolbar.zoom() if the backend is TkAgg which then shows a "+" cursor or to not set pan mode at all for any backend, as this can be selected by the appropriate button in the matplotlib window.

Cheers
Paul

**Comment by trmrsh** [comment]
Implemented this Paul
