### ISSUE TITLE
Implement high red bias warning

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#71]
With the HiPERCAM pipeline now in routine use for ULTRACAM runs at the NTT, it would be useful to replicate the high red bias warning option in rtplot (and reduce?) that is available in the ULTRACAM pipeline. It can be an annoying feature at times, e.g. when taking flats, but this is probably a price worth paying for the ability to quickly spot the issue when a science run starts.

**Comment by trmrsh** [comment]
Hi Vik, I have now added these options ('lowlevel', 'highlevel') to rtplot [in trm-dev at the moment]. They seem to work. I will move to the master branch prior to the ULTRACAM run as I think it's ULTRACAM that is affected above all. Closing now.
