### ISSUE TITLE
Seeing plot broken in reduce for binned data?

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#72]
Minimal working example; run0013 on 2019_07_06.

This is 2x2 data. The reduce log file has FWHM values of around 8. rtplot shows the profile has a FWHM of approximately 8 unbinned pixels (0.6"). The DIMM seeing is solidly sub-arcsecond. 

Fitting with a gaussian to the raw (binned) data give FWHM ~ 4.

The seeing plot in reduce is showing 1.6". I'm thinking the x2 factor for the binning is getting applied twice somehow...

**Comment by StuartLittlefair** [comment]
This is actually quite bizarre, because an identical setup (run0015 on 2019_07_06) doesn't show this issue - the reduce plot looks fine, even though the FWHM values in the reduced log file are very similar!

**Comment by trmrsh** [comment]
Very weird. It's not just a matter of funny pixel scales (arcsec/pix) in the reduce .red file then?

**Comment by StuartLittlefair** [comment]
No; they're all 0.08 arcsec per pixel.

Unless this recurs I'd just chalk it up to weirdness

**Comment by trmrsh** [comment]
them (google drive?)

**Comment by trmrsh** [comment]
sorry that's annoying: I meant to say good if data & reduce could be put somewhere I can access them

**Comment by StuartLittlefair** [comment]
I've uploaded the data to https://drive.google.com/drive/folders/1SmqTrnxcbcOSlBy-xNUdKLXiU3zX-7OJ?usp=sharing

This hasn't happened since.

**Comment by trmrsh** [comment]
Closing. Doesn't seem to happen any more
