### ISSUE TITLE
Issue with aperture plotting in reduce

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#73]
we are reducing data with variable aperture sizes and positions, but the size and position of the apertures in the image plot remains fixed! See the plot below

![bad_reduce_plot](https://user-images.githubusercontent.com/4570807/60846796-16d77800-a1d0-11e9-85aa-6e7e7b2db809.png)

The logfile shows variable aperture positions and FWHM, but both are fixed on the plot...

**Comment by StuartLittlefair** [comment]
This is version 0.18.1.dev125+g45d3fbb

**Comment by StuartLittlefair** [comment]
The problem is [L827](https://github.com/HiPERCAM/hipercam/blob/master/hipercam/reduction.py#L827) in reduction.py. It is pulling the aperture positions straight from the reduction file, but it should be unpacking them from ```results```. I haven't implemented a fix because it's a bit confusing how to do this will the parallel nature of reduce.

**Comment by vikdhillon** [comment]
Just spotted the same problem in a reduction I'm doing this morning.
Do you know if it a problem with just the plotting, or are the apertures
really not moving? I suspect the former, looking at the light curve (which
looks ok), but just want to know whether it is ok to continue with the
reduction before the fix is implemented here.

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by vikdhillon** [comment]
Actually, no, it really does seem to be a problem with the apertures not
moving (it isn't just the plot)...

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by vikdhillon** [comment]
Downloaded Stu's updated reduction.py and all is working now.

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by vikdhillon** [comment]
Sorry - realised that the autoguider was obviously not being used in the
NTT data I'm reducing and it started at a really high airmass, which fooled
me into thinking it wasn't just the plotting of the apertures that was at
fault - this was wrong: it was just the plotting that was failing.

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by trmrsh** [comment]
i am going to merge Stu's pull request which I think fixes this issue.

tom

On Wed, 10 Jul 2019 at 10:49, vikdhillon <notifications@github.com<mailto:notifications@github.com>> wrote:
Sorry - realised that the autoguider was obviously not being used in the
NTT data I'm reducing and it started at a really high airmass, which fooled
me into thinking it wasn't just the plotting of the apertures that was at
fault - this was wrong: it was just the plotting that was failing.

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk<http://www.vikdhillon.staff.shef.ac.uk>
---

**Comment by trmrsh** [comment]
Think this is fixed.
