### ISSUE TITLE
genred failure

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hipercam#84]
Hi Tom

Testing genred on hipercam and ultraspec data yields this...

genred
apfile - aperture input file [run0032]: 
rfile - reduce output file [run0032]: 
comment - user comment to add [<cr> for newline to get multilines] []: 
bias - bias frame ['none' to ignore] [bias_slow_2x2]: bias2x2_slow
flat - flat field frame ['none' to ignore] [kg5flat]: skyflat
dark - dark field frame ['none' to ignore] [none]: 
fmap - fringe frame ['none' to ignore] [none]: 
linear - linear light curve plot? [False]: 
Traceback (most recent call last):
  File "/usr/local/bin/genred", line 8, in <module>
    sys.exit(genred())
  File "/usr/local/lib/python3.7/dist-packages/hipercam/scripts/genred.py", line 595, in genred
    "sinner", "inner sky aperture radius [unbinned pixels]", 30.0, rmax
UnboundLocalError: local variable 'rmax' referenced before assignment

**Comment by trmrsh** [comment]
Fixed
