### ISSUE TITLE
Add readout border to nrtplot

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hipercam#86]
Add blue line to indicate dividing line between readout sectors for ULTRACAM and HiPERCAM.

**Comment by StuartLittlefair** [comment]
Definitely plus one for this. Quite urgent as I had to re-do an acquisition with ULTRACAM because I was too close to the edge

**Comment by trmrsh** [comment]
OK, working on it. Realised what the basic issue is now.

**Comment by trmrsh** [comment]
This is now fixed in trm-dev.
