### ISSUE TITLE
genred uses wrong colours when using ULTRACAM

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#88]
To replicate: reduce ULTRACAM data. I had 3 apertures. I'm not sure this is significant.

Genred allocates the following colours: 

- CCD1 (red CCD) - green
- CCD2 (green CCD) - blue
- CCD3 (blue CCD) - red

**Comment by trmrsh** [comment]
Ah, instrument was not being recognised properly when setting colours. Fixed in trm-dev.
