### ISSUE TITLE
`makeflat` should show you the resulting flat field image

### ISSUE THREAD

**Issue by wildjames** [HiPERCAM/hipercam#89]
I've formed the habit of always checking the flat field images for blemishes and stars that failed to median out, but it's just occurred to me that this should be (and I hope I'm not jinxing it here) fairly easy to implement at the end of running `makeflat`. Should make it more obvious that there is such a thing as a bad flat!

**Comment by trmrsh** [comment]
Certainly a good idea to look at the flat, but how can you be sure that what you see is not real or not? I always tend to try it out with differing values of ngroup and then compare the results which is a rather different thing. Not averse to an automated display, but probably won't get around myself to adding it for a while. If you want to add yourself, feel free to submit a "pull request" (think that's the lingo). Will leave this open as a reminder to me.
