### ISSUE TITLE
joinup

### ISSUE THREAD

**Issue by tariq-shahbaz** [HiPERCAM/hipercam#96]
Hi All

I get the error below when I use joinup. I am using the most current version of the pipeline

joinup source=hl run=run0014 first=1 last=0 ccd=4 trim=yes aper=run0014 bias=bias flat=flat dark=none fmap=none \\
However if I use aper=none,  it seems to work.
Any suggestions?

  warnings.warn(
1, utc= 2021-05-12 02:06:10.538 (ok)
Traceback (most recent call last):
  File "/opt/python/python3.8/bin/joinup", line 8, in <module>
    sys.exit(joinup())
  File "/opt/python/python3.8/lib/python3.8/site-packages/hipercam/scripts/joinup.py", line 751, in joinup
    if expand:
UnboundLocalError: local variable 'expand' referenced before assignment

**Comment by trmrsh** [comment]
That looks like a bug. Will look into it.

**Comment by trmrsh** [comment]
hi Tariq, could you e-mail me your version of joinup.py? Line 751 in my version reads:

                     `   fp.write(DS9_REG_HEADER`

which makes no sense cf the error -- there is a line `if expand` 2 lines later but I am wondering if we have the same version. I will carry on looking to see I can see where there might be a problem even so

**Comment by tariq-shahbaz** [comment]
file attached

Cheers

Tariq

**Comment by trmrsh** [comment]
Somehow it didn't seem to be attached, but no worries, I spotted the problem and have fixed it. As before I have pushed it to the development branch trm-dev, but not the main one as yet.
