### ISSUE TITLE
redanal

### ISSUE THREAD

**Issue by tariq-shahbaz** [HiPERCAM/hipercam#97]
I was looking at redanal.py and there I think there is a tiny mistake in the code line 82 and 83
                xdiffs = x[ok][1:] - x[ok][:-1]                
                ydiffs = x[ok][1:] - x[ok][:-1]
Maybe the ydiff should be
                ydiffs = y[ok][1:] - y[ok][:-1]

**Comment by trmrsh** [comment]
Cheers Tariq. Spot on. Thnaks for the report. I have fixed this and pushed it to my development branch (trm-dev) as opposed to the main branch. I don't know how you handle your installation, but you can easily switch to another branch (git checkout trm-dev), then use git pull to get the latest stuff [you can always use trm-dev if you want to get the very latest, but it's very much "beta" and slightly dodgy]. Alternatively if it's not too burning an issue for you, you could wait until I merge it into the main branch and update then.
