### ISSUE TITLE
hpackage

### ISSUE THREAD

**Issue by tariq-shahbaz** [HiPERCAM/hipercam#98]
There seems to ba a minot bug in hpackage wqhen using tar=True. 

Hope this can be fixed

Cheers

Tariq

hpackage
runs = run0014
dname = run0014
tar = True
Will write files to /home/tsh/.hipercam/tmp/run0014
run0014 run0014 run0014.hcm

None
source = hf
flist = run0014
trim = False
ccd = 0
aper = run0014.ape
msub = False
dtype = float32
dmax = 100.0
nmax = 100
overwrite = False
compress = rice
odir = /home/tsh/.hipercam/tmp/run0014
1, utc= 2021-05-12 02:06:10.538 (ok)
   CCD 1: added WCS
   CCD 1: written /home/tsh/.hipercam/tmp/run0014/run0014_ccd1.fits
   CCD 1: written ds9 region file /home/tsh/.hipercam/tmp/run0014/run0014_ccd1.reg
   CCD 2: added WCS
   CCD 2: written /home/tsh/.hipercam/tmp/run0014/run0014_ccd2.fits
   CCD 2: written ds9 region file /home/tsh/.hipercam/tmp/run0014/run0014_ccd2.reg
   CCD 3: added WCS
   CCD 3: written /home/tsh/.hipercam/tmp/run0014/run0014_ccd3.fits
   CCD 3: written ds9 region file /home/tsh/.hipercam/tmp/run0014/run0014_ccd3.reg
   CCD 4: added WCS
   CCD 4: written /home/tsh/.hipercam/tmp/run0014/run0014_ccd4.fits
   CCD 4: written ds9 region file /home/tsh/.hipercam/tmp/run0014/run0014_ccd4.reg
   CCD 5: added WCS
   CCD 5: written /home/tsh/.hipercam/tmp/run0014/run0014_ccd5.fits
   CCD 5: written ds9 region file /home/tsh/.hipercam/tmp/run0014/run0014_ccd5.reg
Written 5 FITS files to disk.
copied run0014.hcm to /home/tsh/.hipercam/tmp/run0014/run0014.hcm
copied run0014.ape to /home/tsh/.hipercam/tmp/run0014/run0014.ape
copied run0014.red to /home/tsh/.hipercam/tmp/run0014/run0014.red
copied run0014.log to /home/tsh/.hipercam/tmp/run0014/run0014.log
Loaded ASCII log = run0014.log
Writing to disk in file = /home/tsh/.hipercam/tmp/run0014/run0014.fits
Converted run0014.log to /home/tsh/.hipercam/tmp/run0014/run0014.fits
removing temporary directory /home/tsh/.hipercam/tmp/run0014
Traceback (most recent call last):
  File "/opt/python/python3.8/bin/hpackage", line 8, in <module>
    sys.exit(hpackage())
  File "/opt/python/python3.8/lib/python3.8/site-packages/hipercam/scripts/hpackage.py", line 225, in hpackage
    raise HipercamError(
NameError: name 'HipercamError' is not defined

**Comment by tariq-shahbaz** [comment]
Hi Tom

My bias and flats are in a different directly, ie
bias=../bias/bias_1x1_slow_ff
so that is why it did not work. Once they are in the same directory it
works.

Thanks

Tariq

**Comment by trmrsh** [comment]
Ah, OK, yes looking at the code, I see I am insisting on the calibration files being in the same directory as the script was invoked from. I wonder why I imposed that?

**Comment by trmrsh** [comment]
(I tend to use a lot of soft-links for calibration so they are always in the same dir)

**Comment by trmrsh** [comment]
Oh, I remember now: my aim was that when the files are copied you could in principle re-run the reduction straight off provide you had the raw data somewhere. This doesn't work if the calibration files are in other directories.

**Comment by tariq-shahbaz** [comment]
In fact what I am really using hpackage for is to write out the individual
ccd images of an average run(biased an flats fielded), with the WCS added.

I thought joinup would so that, but it seems I have to use joinup (with the
bias and flat) and then average the fits images in iraf.

BTW is there a way to use the pipeline to average fits images. Combine
requires hcm files when I use source=hf

Tariq
